// Generated by `npm run optimize-images` — do not edit by hand.

export type WorldImageSet = {
  /** Content hash of the source photo; appended to URLs so files can be cached forever. */
  v: string;
  /** Pixel size of the largest hero rung. */
  width: number;
  height: number;
  /** Available widths, ascending. The last one is the un-suffixed file. */
  hero: number[];
  card: number[];
  /** width / height of the card crop. */
  cardRatio: number;
  blur: string;
};

export const worldImages: Record<string, WorldImageSet> = {
  "auto": {
    "v": "b55bfc09",
    "width": 1920,
    "height": 2880,
    "hero": [
      640,
      1024,
      1440,
      1920
    ],
    "card": [
      480,
      800
    ],
    "cardRatio": 1.3333,
    "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwAwCdASoQABgAPu1iqU2ppaQiMAgBMB2JbACo9CHSRKn277aVJRAgAP70HyftCmR/mrYrHrvgHN7jyNYnP6Na5UU/x7dAcBglNIEv1y9MJWsR73yQgwFL7uA4VBFXoPtVQ0p1YnN1y9l38k2nrLiH9S7u0AAA"
  },
  "bus": {
    "v": "9a77953c",
    "width": 1920,
    "height": 2397,
    "hero": [
      640,
      1024,
      1440,
      1920
    ],
    "card": [
      480,
      800
    ],
    "cardRatio": 1.3333,
    "blur": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JagCo9ywBn7TTscaKHfdo3ErcAP7vHHaHkplWhEeBLg118LZmIz7gM/Tc0Ld/5w+MyaYbiscRpvNbmQYq5ulvMcZlFCjnEuu0/sKOGQ8Ezgjbygk5r+NvCd96avjYcFoRKFD4uEkW3nrDzMgTMjr8qTN/Nztx7z7ecAAA"
  },
  "monsoon": {
    "v": "f07ad238",
    "width": 1920,
    "height": 2880,
    "hero": [
      640,
      1024,
      1440,
      1920
    ],
    "card": [
      480,
      800
    ],
    "cardRatio": 1.3333,
    "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JQBfnBF3W2VFw1+TnKP2IrwAA/vGE5wzt6/ks3gUTuiNRgc0S8nP22WjWp75ZwJk2aU9dwVDI7CB1P91CK7j3w3X8VFFdIsxxJqLc3mtWse51UCK+ItnhBNPDf5XsG6Kn3waB6YAAAA=="
  },
  "saloon": {
    "v": "d2f4e38a",
    "width": 1920,
    "height": 1080,
    "hero": [
      640,
      1024,
      1440,
      1920
    ],
    "card": [
      480,
      800
    ],
    "cardRatio": 1.7778,
    "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAQCdASoQAAkAA4BaJQBOgCB1bn/wAPsFIbdUka3OfJHoTrwcdQvzB62NZmymbq1c9zpWthEZyJQrsefZ++J3vrc87drZNSLeACe/xgAAAA=="
  },
  "tapri": {
    "v": "c4523b97",
    "width": 1920,
    "height": 1280,
    "hero": [
      640,
      1024,
      1440,
      1920
    ],
    "card": [
      480,
      800
    ],
    "cardRatio": 1.5,
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAQCdASoQAAsAA4BaJYwATgAF79AwAAD+7s4tNVyT4CEO64+bxThKJ9kPEJZNe6k+ElFWePGrg0NfI8uOp7ejQDDNsUPq2JNO8F031OgnT+c8fnbY0kb9m+7bxcAA"
  }
};
